name: asdf  # check to see if it's available
version: git
summary: I was bored... # 79 char long summary
description: |
  This is likely the dumbest thing you've ever installed. 
grade: stable # must be 'stable' to release into candidate/stable channels
confinement: strict # use 'strict' once you have the right plugs

apps:
  asdf:
    command: python3 $SNAP/bin/asdf.py
     
parts: 
  asdf:
    source: https://github.com/kz6fittycent/asdf
    source-type: git
    plugin: python
    python-version: python3
    
    build-packages:
      - python3
      
    stage-packages:
      - python3

  publish:
    plugin: copy
    files:
      ./asdf.py: bin/asdf.py
